//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.30 at 10:27:29 AM SGT 
//
package jaxb.weka.associations;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="config" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="associatior" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="defaults" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "config"
})
@XmlRootElement(name = "associations")
public class Associations {

    protected List<Associations.Config> config;

    /**
     * Gets the value of the config property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the config property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfig().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Associations.Config }
     *
     *
     */
    public List<Associations.Config> getConfig() {
        if (config == null) {
            config = new ArrayList<Associations.Config>();
        }
        return this.config;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="associatior" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="defaults" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "associatior",
        "defaults"
    })
    public static class Config {

        @XmlElement(required = true)
        protected String associatior;
        @XmlElement(required = true)
        protected String defaults;

        /**
         * Gets the value of the associatior property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getAssociatior() {
            return associatior;
        }

        /**
         * Sets the value of the associatior property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setAssociatior(String value) {
            this.associatior = value;
        }

        /**
         * Gets the value of the defaults property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getDefaults() {
            return defaults;
        }

        /**
         * Sets the value of the defaults property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setDefaults(String value) {
            this.defaults = value;
        }

        @Override
        public String toString() {

            String[] assc = this.associatior.split("\\s");
            int lastOccur = assc[0].lastIndexOf(".");
            String simplifiedTask = assc[0].substring(lastOccur + 1);
            return simplifiedTask;
        }

    }

}
