
package mz.com.wsweka;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ElearningWekaWSService", targetNamespace = "http://wsweka/", wsdlLocation = "http://localhost:9876/elearningwekaws?wsdl")
public class ElearningWekaWSService
    extends Service
{

    private final static URL ELEARNINGWEKAWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ELEARNINGWEKAWSSERVICE_EXCEPTION;
    private final static QName ELEARNINGWEKAWSSERVICE_QNAME = new QName("http://wsweka/", "ElearningWekaWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/elearningwekaws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ELEARNINGWEKAWSSERVICE_WSDL_LOCATION = url;
        ELEARNINGWEKAWSSERVICE_EXCEPTION = e;
    }

    public ElearningWekaWSService() {
        super(__getWsdlLocation(), ELEARNINGWEKAWSSERVICE_QNAME);
    }

    public ElearningWekaWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ELEARNINGWEKAWSSERVICE_QNAME, features);
    }

    public ElearningWekaWSService(URL wsdlLocation) {
        super(wsdlLocation, ELEARNINGWEKAWSSERVICE_QNAME);
    }

    public ElearningWekaWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ELEARNINGWEKAWSSERVICE_QNAME, features);
    }

    public ElearningWekaWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ElearningWekaWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ElearningWekaWS
     */
    @WebEndpoint(name = "ElearningWekaWSPort")
    public ElearningWekaWS getElearningWekaWSPort() {
        return super.getPort(new QName("http://wsweka/", "ElearningWekaWSPort"), ElearningWekaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ElearningWekaWS
     */
    @WebEndpoint(name = "ElearningWekaWSPort")
    public ElearningWekaWS getElearningWekaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsweka/", "ElearningWekaWSPort"), ElearningWekaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ELEARNINGWEKAWSSERVICE_EXCEPTION!= null) {
            throw ELEARNINGWEKAWSSERVICE_EXCEPTION;
        }
        return ELEARNINGWEKAWSSERVICE_WSDL_LOCATION;
    }

}
