//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 03:35:42 PM SGT 
//


package moodle.xml.response;

import javax.xml.bind.annotation.XmlRegistry;
import moodle.xml.response.RESPONSE;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the moodleresponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: moodleresponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RESPONSE.SINGLE.KEY.MULTIPLE.SINGLE.KEY }
     * 
     */
    public RESPONSE.SINGLE.KEY createRESPONSESINGLEKEYMULTIPLESINGLEKEY() {
        return new RESPONSE.SINGLE.KEY();
    }

    /**
     * Create an instance of {@link RESPONSE.SINGLE }
     * 
     */
    public RESPONSE.SINGLE createRESPONSESINGLE() {
        return new RESPONSE.SINGLE();
    }

    /**
     * Create an instance of {@link RESPONSE.SINGLE.KEY.MULTIPLE }
     * 
     */
    public RESPONSE.SINGLE.KEY.MULTIPLE createRESPONSESINGLEKEYMULTIPLE() {
        return new RESPONSE.SINGLE.KEY.MULTIPLE();
    }

    /**
     * Create an instance of {@link RESPONSE.SINGLE.KEY }
     * 
     */
    public RESPONSE.SINGLE.KEY createRESPONSESINGLEKEY() {
        return new RESPONSE.SINGLE.KEY();
    }

    /**
     * Create an instance of {@link RESPONSE.SINGLE.KEY.MULTIPLE.SINGLE }
     * 
     */
    public RESPONSE.SINGLE createRESPONSESINGLEKEYMULTIPLESINGLE() {
        return new RESPONSE.SINGLE();
    }

    /**
     * Create an instance of {@link RESPONSE }
     * 
     */
    public RESPONSE createRESPONSE() {
        return new RESPONSE();
    }

}
