//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 05:39:23 PM SGT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tempuri.org/XMLSchema1.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mz.com.expert;
